### ISSUE TITLE
Clay and realtime audio mixing/dsp?

### ISSUE THREAD

**Issue by cambiata** [RudenkoArts/clay2d#3]
Hi Andrei!

Can I do realtime audio mixing and dsp stuff in Clay?

// Jonas

**Comment by AndreiRudenko** [comment]
Hey, yes, there is some effects in clay/audio/effects folder as example. Basically i just use Kha.audio2 api for dsp. For now im not quite sure about stability of native targets, but i'm working on it.

**Comment by cambiata** [comment]
Cool, thanks!

**Comment by cambiata** [comment]
Got audio mixing on standard Kha working on Android native. Simple test seems to be working fine. 
Haven't had time or machine for iOS yet...
